version: '3.2'

services:
  mongodb:
    image: mongo:latest
    container_name: "mongodb"
    environment:
      - MONGO_DATA_DIR=/data/db
      - MONGO_LOG_DIR=/dev/null
    volumes:
      - /data/db:/data/db
    ports:
      - 27017:27017
    command: mongod --smallfiles --storageEngine=wiredTiger --logpath=/dev/null # --quiet

  nsqlookup:
    image: nsqio/nsq
    hostname: nsqlookup
    ports:
      - "4160:4160"
      - "4161:4161"
    command: /nsqlookupd

  nsq:
    image: nsqio/nsq
    hostname: nsq
    ports:
      - "4150:4150"
      - "4151:4151"
    links:
      - nsqlookup:nsqlookup
    command: /nsqd --broadcast-address nsq --lookupd-tcp-address=nsqlookup:4160 --msg-timeout=30m --max-msg-timeout=60m

  nsqadmin:
    image: nsqio/nsq
    hostname: nsqadmin
    links:
      - nsqlookup:nsqlookup
    ports:
      - "4171:4171"
    command: /nsqadmin --lookupd-http-address=nsqlookup:4161