version: '3.2'

services:
  mongodb:
    image: mongo:latest
    container_name: "mongodb"
    environment:
      - MONGO_DATA_DIR=/data/db
      - MONGO_LOG_DIR=/dev/null
    volumes:
      - ./data/db:/data/db
    ports:
      - 27017:27017
    command: mongod --smallfiles --storageEngine=wiredTiger --logpath=/dev/null # --quiet

  rabbit:
    environment:
      - RABBITMQ_ERLANG_COOKIE='secret_cookie'
    networks:
      - back
    hostname: rabbit_node_1
    image: "rabbitmq:3-management"
    ports:
      - "15672:15672"
      - "5672:5672"
    tty: true
    volumes:
      - rabbit1:/var/lib/rabbitmq
      - ./conf/:/etc/rabbitmq/
    command:  bash -c "sleep 10; rabbitmq-server;"

  nsqlookup:
    image: nsqio/nsq
    hostname: nsqlookup
    ports:
      - "4160:4160"
      - "4161:4161"
    command: /nsqlookupd

  nsq:
    image: nsqio/nsq
    hostname: nsq
    ports:
      - "4150:4150"
      - "4151:4151"
    links:
      - nsqlookup:nsqlookup
    command: /nsqd --broadcast-address nsq --lookupd-tcp-address=nsqlookup:4160 --msg-timeout=30m --max-msg-timeout=60m

  nsqadmin:
    image: nsqio/nsq
    hostname: nsqadmin
    links:
      - nsqlookup:nsqlookup
    ports:
      - "4171:4171"
    command: /nsqadmin --lookupd-http-address=nsqlookup:4161

volumes:
  rabbit1:
    driver: local

networks:
  back: