apps:
  - script: index.js
    name: scanner
    instances: 1
    exec_mode: fork
    args: --expose-gc

  - script: pending-transactions.js
    name: pending-transactions-scanner
    instances: 1
    exec_mode: fork
    args: --expose-gc

  - script: ./ethereum/workers/blocks/index.js
    name: blocks-listner
    instances: 1
    exec_mode: fork
    autorestart: true
    args: --expose-gc

  - script: ./ethereum/workers/blocks/index.js
    name: catching-up-blocks-listner
    instances: 1
    exec_mode: fork
    autorestart: true
    args: --expose-gc
    env:
      CATCHING_UP_MODE: true

  - script: ./ethereum/workers/blocks/processing.js
    name: transactions-listner
    instances: 3
    exec_mode: fork
    autorestart: true
    args: --expose-gc

  - script: ./ethereum/workers/pending-transactions.js
    name: pending-transactions-worker
    instances: 1
    exec_mode: fork
    autorestart: true
    args: --expose-gc