apps:
  - script: index.js
    name: scanner
    instances: 1
    exec_mode: fork
    args: --expose-gc

  - script: ./ethereum/listeners/blocks/index.js
    name: blocks-listner
    instances: 1
    exec_mode: fork
    autorestart: true
    args: --expose-gc

  - script: ./ethereum/listeners/blocks/contracts.js
    name: transactions-listner
    instances: 3
    exec_mode: fork
    autorestart: true
    args: --expose-gc